name: 'Deploy to AWS S3'
description: 'Deploy static website to AWS S3'
inputs:
  bucket:
    description: 'Name of the S3 bucket'
    required: true
  bucket-region:
    description: 'Region of the S3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'Name of the folder in the repository to deploy'
    required: true
runs:
  using: 'node20'
  main: 'main.js'
